language: node_js
node_js:
- 9.10.1
deploy:
  provider: heroku
  app: brint-server
  on:
    repo: Harrisandwich/brint-server
  api_key:
    secure: Tet/nHSU70ZLG7ftW1MhgpFkcz29p2YlyKXrIH0iT+xukn7AJpo4P+YezrxHSDZr+NHZIu1dXD7CEqNV2dWk/YnTZd33jFcLbMdsLCp82eU7kziwnrNTlH4ENmwOPSeEV45uYSG0AZHkUMCfRAtHbtjvYWd1SsigCfuQofF2kFiXVsjdkzWO8e33b2GkZw1NO0fIdUjea2xvTt39PCJf1BfTz1oywVZf1jHJamqUNzJUeCYwCN1W8OWjmiJDiEoANy0LUfYeSulKPSAuinRXSXrrkb4kMCtDQ763DnDHOi5sllt5fWI+EpYDWOsGloIgltWYPZGi5vju09ZQoXJWgL7/Wn5vj5i749a69PLtz9uBc2A0Uk2u1VXEku9EmHY2f2hdije5Wfq0PTpQnNHiyDsltPs30NK+xaidqP4LV0/1NE0BvfqHeKqbVKDhjOSSqyrqJtuOgEvz9yqIRM1S/b+CatY/U8OE8o5xoEe6oszFryPrZgfvV3kazUGNCYqXINgpbhCEff4+Whs0vLm0Q+SjLxy8MP12wouZcvT28T1Muc32nMNSrwgSbPMmsAzzSmYO9mLhWzZOc4YtkIqqtojKDQjkCNikhsCgtMp/i7HnfLQ0oUDUtA0J2Bqx0vISSM1yAbi/cF2cxnWfeIu6jLnGnKkadm4N0t7EcCONzN4=
